# Torch Import

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0


In [2]:
torch.cuda.is_available()

True

In [3]:
!nvidia-smi

Mon Jan  2 21:07:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:A1:00.0 Off |                  N/A |
|  0%   25C    P8    15W / 370W |      2MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:C1:00.0 Off |                  N/A |
|  0%   

# Access GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 3090'

In [8]:
torch.cuda.get_arch_list()

['sm_37',
 'sm_50',
 'sm_60',
 'sm_61',
 'sm_70',
 'sm_75',
 'sm_80',
 'sm_86',
 'compute_37']

In [10]:
torch.cuda.get_device_properties(0)

_CudaDeviceProperties(name='NVIDIA GeForce RTX 3090', major=8, minor=6, total_memory=24268MB, multi_processor_count=82)

In [11]:
torch.cuda.get_device_properties(1)

_CudaDeviceProperties(name='NVIDIA GeForce RTX 3090', major=8, minor=6, total_memory=24268MB, multi_processor_count=82)

# Intro to Tensors

tensor 생성

In [22]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

생성한 tensor의 dimension 확인

In [17]:
scalar.ndim

0

tensor의 내용물을 python `int` 로 return

In [18]:
scalar.item()

7

Vector 생성

In [23]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [24]:
vector.ndim

1

In [30]:
vector.shape

torch.Size([2])

Matrix 생성

In [36]:
#Matrix
Matrix = torch.tensor([[7, 7], [8, 8]])
Matrix

tensor([[7, 7],
        [8, 8]])

In [37]:
Matrix.ndim

2

In [38]:
Matrix[0]

tensor([7, 7])

In [39]:
Matrix[1]

tensor([8, 8])

In [40]:
Matrix.shape

torch.Size([2, 2])

Tensor 생성

In [42]:
#tensor
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [43]:
TENSOR.ndim

3

In [44]:
TENSOR.shape

torch.Size([1, 3, 3])

In [45]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [50]:
TENSOR[0][0]

tensor([1, 2, 3])

# Create Random Tensors

In [54]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3324, 0.4391, 0.7235, 0.6145],
        [0.4723, 0.4895, 0.8842, 0.5419],
        [0.5977, 0.5812, 0.8783, 0.7066]])

In [60]:
random_tensor.ndim

2

In [63]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros & Ones

In [64]:
torch.rand(size=(3, 3))

tensor([[7.6168e-01, 3.2221e-01, 4.9105e-01],
        [7.6151e-01, 3.7821e-02, 1.9138e-01],
        [1.7881e-04, 4.2003e-01, 5.4702e-01]])

In [73]:
ZEROS = torch.zeros(3,4)
ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [78]:
ZEROS.dtype

torch.float32

In [75]:
# masking
ZEROS*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [76]:
ONES = torch.ones(3, 3)
ONES

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [79]:
ONES.dtype

torch.float32

In [77]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [90]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
one_to_ten.shape

torch.Size([10])

In [93]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [94]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor Datatypes

In [99]:
#float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], 
    dtype=None,
    device=None,
    requires_grad=False)

float_32_tensor

tensor([3., 6., 9.])

In [97]:
float_32_tensor.dtype # None으로 세팅해도 default가 float32라서 float32가 출력됨

torch.float32

In [103]:
float_16_tensor = float_32_tensor.type(torch.float16) # float16=half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)